/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package energysimulator;

import SimulationLib.FuelType;
import SimulationLib.Simulator;
import java.text.DecimalFormat;

/**
 *
 * @author hh7g19
 */
public class FloorPlan1 extends javax.swing.JFrame {
    
    
    
    double gas;
    double elec;
    double total;
    
    private static DecimalFormat df2  = new DecimalFormat("##.##"); //2.dp

//    void runInBackbround(){
//        new Thread(new Runnable() {
//        @Override
//        public void run() {
//            // DO your work here
//            // get the data
//            
//                runOnUiThread(new Runnable() {
//                    @Override
//                    public void run() {
//                        // update UI
//                        runInBackground();
//                    }
//                });
//            } else {
//                runInBackground();
//            }
//        }
//    }).start();
//    }
//AsyncTask.execute(new Runnable() {
    /**
     * Creates new form FloorPlan1
     */
    public FloorPlan1() {
        initComponents();
    }
//    
//    Thread thread = new Thread(this);
//        thread.start();
//        try {
//            latch.await();
//        } catch (InterruptedException e) {
//           /// e.printStackTrace();
//        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        consoleOnButton = new javax.swing.JButton();
        consoleOffButton = new javax.swing.JButton();
        consoleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        speakerOnButton = new javax.swing.JButton();
        speakerOffButton = new javax.swing.JButton();
        speakerLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rad1on = new javax.swing.JButton();
        rad1off = new javax.swing.JButton();
        rad1label = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tvOnButton = new javax.swing.JButton();
        tvOffButton = new javax.swing.JButton();
        tvLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        oven1on = new javax.swing.JButton();
        ovenoff1 = new javax.swing.JButton();
        oven1label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        ToConsump = new javax.swing.JLabel();
        gaslabel2 = new javax.swing.JLabel();
        eleclabel1 = new javax.swing.JLabel();
        ElecCons = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        GasCons = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        consoleOnButton.setText("On");
        consoleOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleOnButtonActionPerformed(evt);
            }
        });
        jPanel5.add(consoleOnButton);

        consoleOffButton.setText("off");
        consoleOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consoleOffButtonActionPerformed(evt);
            }
        });
        jPanel5.add(consoleOffButton);

        consoleLabel.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/consoleOff.png")); // NOI18N
        jPanel5.add(consoleLabel);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(100, 50, 170, 100);

        jPanel1.setLayout(null);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(75, 39, 0, 0);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(37, 11, 0, 0);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 10, 0, 0);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        speakerOnButton.setText("On");
        speakerOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakerOnButtonActionPerformed(evt);
            }
        });
        jPanel6.add(speakerOnButton);

        speakerOffButton.setText("off");
        speakerOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakerOffButtonActionPerformed(evt);
            }
        });
        jPanel6.add(speakerOffButton);

        speakerLabel.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/speakerOff.jpeg")); // NOI18N
        jPanel6.add(speakerLabel);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(80, 160, 180, 110);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rad1on.setText("On");
        rad1on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1onActionPerformed(evt);
            }
        });
        jPanel2.add(rad1on);

        rad1off.setText("off");
        rad1off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1offActionPerformed(evt);
            }
        });
        jPanel2.add(rad1off);

        rad1label.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/Rad Off.png")); // NOI18N
        jPanel2.add(rad1label);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(630, 380, 160, 110);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tvOnButton.setText("On");
        tvOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvOnButtonActionPerformed(evt);
            }
        });
        jPanel4.add(tvOnButton);

        tvOffButton.setText("off");
        tvOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvOffButtonActionPerformed(evt);
            }
        });
        jPanel4.add(tvOffButton);

        tvLabel.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/TV Image.png")); // NOI18N
        jPanel4.add(tvLabel);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(90, 380, 180, 110);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        oven1on.setText("On");
        oven1on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oven1onActionPerformed(evt);
            }
        });
        jPanel3.add(oven1on);

        ovenoff1.setText("off");
        ovenoff1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovenoff1ActionPerformed(evt);
            }
        });
        jPanel3.add(ovenoff1);

        oven1label.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/Oven Off.png")); // NOI18N
        jPanel3.add(oven1label);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(550, 60, 160, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/kieran/Desktop/energySimulator/simple_blanked.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 10, 770, 530);

        jPanel7.setLayout(null);
        jPanel7.add(ToConsump);
        ToConsump.setBounds(170, 90, 90, 20);

        gaslabel2.setText("Gas consumption: £");
        jPanel7.add(gaslabel2);
        gaslabel2.setBounds(30, 50, 126, 16);

        eleclabel1.setText("Electricty consumption: £");
        jPanel7.add(eleclabel1);
        eleclabel1.setBounds(30, 20, 161, 16);
        jPanel7.add(ElecCons);
        ElecCons.setBounds(190, 20, 70, 20);

        jlabel.setText("Total Consumption: £");
        jPanel7.add(jlabel);
        jlabel.setBounds(30, 90, 137, 16);
        jPanel7.add(GasCons);
        GasCons.setBounds(160, 50, 100, 20);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(140, 550, 280, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//    AsyncTask.execute(new Runnable() {
    private void rad1onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1onActionPerformed
        rad1label.setIcon(new javax.swing.ImageIcon("RadOn.png"));
        Simulator sim = new Simulator("cost.csv", "costRate.csv");
        sim.addAppliance("Radiator");
        //isOn = true;
//        while(isOn == true){
        //int hourCount =0; 
        Thread thread = new Thread(new Runnable() {
             public void run() {
            while(!rad1off.isSelected()){
                int hourCount = Timer.startTimer();
                sim.passHour(hourCount);
                System.out.println("Gas: " + sim.totalCostOf(FuelType.Gas).toString());
                gas += sim.totalCostOf(FuelType.Gas);
                total += gas;
                FloorPlan1.GasCons.setText(df2.format(gas));
                FloorPlan1.ToConsump.setText(df2.format(total));
                
            }
             }
        });
        thread.start();
          
    }//GEN-LAST:event_rad1onActionPerformed
//});
    private void rad1offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1offActionPerformed
       rad1label.setIcon(new javax.swing.ImageIcon("Rad Off.png"));
       //isOn = false;
    }//GEN-LAST:event_rad1offActionPerformed

    private void oven1onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oven1onActionPerformed
       oven1label.setIcon(new javax.swing.ImageIcon("Oven On.png"));
       Simulator sim = new Simulator("cost.csv", "costRate.csv");
       sim.addAppliance("Oven");
        //isOn = true;
//        while(isOn == true){
        //int hourCount =0; 
        Thread thread = new Thread(new Runnable() {
             public void run() {
            while(!ovenoff1.isSelected()){
                int hourCount = Timer.startTimer();
                sim.passHour(hourCount);
                System.out.println("Gas: " + sim.totalCostOf(FuelType.Gas).toString());
                gas += sim.totalCostOf(FuelType.Gas);
                total += gas;
                FloorPlan1.GasCons.setText(df2.format(gas));
                FloorPlan1.ToConsump.setText(df2.format(total));
            }
             }
        });
        thread.start();
    }//GEN-LAST:event_oven1onActionPerformed

    private void ovenoff1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovenoff1ActionPerformed
       oven1label.setIcon(new javax.swing.ImageIcon("Oven Off.png"));
    }//GEN-LAST:event_ovenoff1ActionPerformed

    private void tvOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvOnButtonActionPerformed
        tvLabel.setIcon(new javax.swing.ImageIcon("TV Image On.png"));
        Simulator sim = new Simulator("cost.csv", "costRate.csv");
        sim.addAppliance("Television");
        //isOn = true;
//        while(isOn == true){
        //int hourCount =0; 
        Thread thread = new Thread(new Runnable() {
             public void run() {
            while(!tvOffButton.isSelected()){
                int hourCount = Timer.startTimer();
                sim.passHour(hourCount);
                System.out.println("Electricity: " + sim.totalCostOf(FuelType.Electricity).toString());
                elec += sim.totalCostOf(FuelType.Electricity);
                total += elec;
                FloorPlan1.ElecCons.setText(df2.format(elec));
                FloorPlan1.ToConsump.setText(df2.format(total));
            }
             }
        });
        thread.start();
    }//GEN-LAST:event_tvOnButtonActionPerformed

    private void tvOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvOffButtonActionPerformed
        tvLabel.setIcon(new javax.swing.ImageIcon("TV Image.png"));
    }//GEN-LAST:event_tvOffButtonActionPerformed

    private void consoleOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleOnButtonActionPerformed
        consoleLabel.setIcon(new javax.swing.ImageIcon("consoleOn.png"));
        Simulator sim = new Simulator("cost.csv", "costRate.csv");
        sim.addAppliance("Games Console");
        //isOn = true;
//        while(isOn == true){
        //int hourCount =0; 
        Thread thread = new Thread(new Runnable() {
             public void run() {
            while(!consoleOffButton.isSelected()){
                int hourCount = Timer.startTimer();
                sim.passHour(hourCount);
                System.out.println("Electricity: " + sim.totalCostOf(FuelType.Electricity).toString());
                elec += sim.totalCostOf(FuelType.Electricity);
                total += elec;
                FloorPlan1.ElecCons.setText(df2.format(elec));
                FloorPlan1.ToConsump.setText(df2.format(total));
            }
             }
        });
        thread.start();
    }//GEN-LAST:event_consoleOnButtonActionPerformed

    private void consoleOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consoleOffButtonActionPerformed
        consoleLabel.setIcon(new javax.swing.ImageIcon("consoleOff.png"));
    }//GEN-LAST:event_consoleOffButtonActionPerformed

    private void speakerOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakerOnButtonActionPerformed
       speakerLabel.setIcon(new javax.swing.ImageIcon("speakerOn.png"));
       Simulator sim = new Simulator("cost.csv", "costRate.csv");
        sim.addAppliance("Stereo System");
        //isOn = true;
//        while(isOn == true){
        //int hourCount =0; 
        Thread thread = new Thread(new Runnable() {
             public void run() {
            while(!speakerOffButton.isSelected()){
                int hourCount = Timer.startTimer();
                sim.passHour(hourCount);
                System.out.println("Electricity: " + sim.totalCostOf(FuelType.Electricity).toString());
                elec += sim.totalCostOf(FuelType.Electricity);
                total += elec;
                FloorPlan1.ElecCons.setText(df2.format(elec));
                FloorPlan1.ToConsump.setText(df2.format(total));
            }
             }
        });
        thread.start();
    }//GEN-LAST:event_speakerOnButtonActionPerformed

    private void speakerOffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakerOffButtonActionPerformed
       speakerLabel.setIcon(new javax.swing.ImageIcon("speakerOff.jpeg"));
    }//GEN-LAST:event_speakerOffButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FloorPlan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FloorPlan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FloorPlan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FloorPlan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FloorPlan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel ElecCons;
    private static javax.swing.JLabel GasCons;
    private static javax.swing.JLabel ToConsump;
    private javax.swing.JLabel consoleLabel;
    private javax.swing.JButton consoleOffButton;
    private javax.swing.JButton consoleOnButton;
    private javax.swing.JLabel eleclabel1;
    private javax.swing.JLabel gaslabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel oven1label;
    private javax.swing.JButton oven1on;
    private javax.swing.JButton ovenoff1;
    private javax.swing.JLabel rad1label;
    private javax.swing.JButton rad1off;
    private javax.swing.JButton rad1on;
    private javax.swing.JLabel speakerLabel;
    private javax.swing.JButton speakerOffButton;
    private javax.swing.JButton speakerOnButton;
    private javax.swing.JLabel tvLabel;
    private javax.swing.JButton tvOffButton;
    private javax.swing.JButton tvOnButton;
    // End of variables declaration//GEN-END:variables
}
