/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package energysimulator;

/**
 *
 * @author hh7g19
 */
public class Simple_blanked extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public Simple_blanked() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        boiler = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rad_1 = new javax.swing.JLabel();
        rad_2 = new javax.swing.JLabel();
        rad_3 = new javax.swing.JLabel();
        rad1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(48, 110, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Floor Plans\\simple_blanked.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 139, 765, 484);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1019, 302, 100, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(97, 106, 1604, 842);

        jPanel3.setLayout(null);

        jButton2.setText("jButton2");
        jPanel3.add(jButton2);
        jButton2.setBounds(150, 210, 73, 23);

        boiler.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Boiler_Off - Copy.jpg")); // NOI18N
        jPanel3.add(boiler);
        boiler.setBounds(870, 320, 97, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Oven Off.png")); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(870, 120, 130, 160);

        rad_1.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Rad Off.png")); // NOI18N
        jPanel3.add(rad_1);
        rad_1.setBounds(70, 300, 250, 170);

        rad_2.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Rad Off.png")); // NOI18N
        jPanel3.add(rad_2);
        rad_2.setBounds(1280, 690, 250, 190);

        rad_3.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Rad Off.png")); // NOI18N
        jPanel3.add(rad_3);
        rad_3.setBounds(70, 730, 250, 190);

        rad1.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Appliances\\Rad Off.png")); // NOI18N
        rad1.setText("rad on");
        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });
        jPanel3.add(rad1);
        rad1.setBounds(1060, 440, 370, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon("filestore.soton.ac.uk\\users\\hh7g19\\mydocuments\\Microhack\\MicroHack-master\\MicroHack-master\\critical_software\\ECSS Hackathon Files\\Floor Plans\\simple_blanked.jpg")); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(40, 30, 1550, 1020);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(110, 10, 1730, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
        rad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RadOn.png")));
    }//GEN-LAST:event_rad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simple_blanked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simple_blanked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simple_blanked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simple_blanked.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simple_blanked().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boiler;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton rad1;
    private javax.swing.JLabel rad_1;
    private javax.swing.JLabel rad_2;
    private javax.swing.JLabel rad_3;
    // End of variables declaration//GEN-END:variables
}
